### ISSUE TITLE
How do you setup using multiple RSA keys?

### ISSUE THREAD

**Issue by echan00** [hausgold/grape-jwt-authentication#5]
Thanks for this awesome library. 

It would be a problem if one of my users loses their public RSA key and my server is not able to disable its usage. I'm hoping to issue RSA key pairs per each user (instead of one key pair for all users) interacting with my server to overcome this problem. 

Is this the right way to do it? How would I set this up with this library? 

To clarify, `conf.rsa_public_key_url` assumes I am using the same RSA key pairs for all authentication, should this be dynamic so that I can retrieve the appropriate public key?

**Comment by echan00** [comment]
Okay, I think I misunderstood how JWTs work. Actually the RSA keys (public and private) are kept by the authenticating server

**Comment by Jack12816** [comment]
Sorry for responding this late, but yep. You just need one RSA keypair for all users.
